import "./globals.css";
import { Archivo } from "next/font/google";

const archivo = Archivo({ subsets: ["latin"] });

export const metadata = {
  title: "Bejamas Test Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={archivo.className}>
        <div className="flex justify-center ">
          <div className="border-2 border-red-400 container">{children}</div>
        </div>
      </body>
    </html>
  );
}
